### ISSUE TITLE
Tamil Nadu population counts for gender don't add up to total

### ISSUE THREAD

**Issue by themonk911** [GoogleCloudPlatform/covid-19-open-data#130]
From https://open-covid-19.github.io/explorer/report/?key=IN_TN,

population | 72,147,030
population_male | 41,657,119
population_female | 41,010,202

**Comment by owahltinez** [comment]
This is due to population coming from Wikipedia and male/female breakdowns being estimated from WorldPop. I'm not sure that we want to use estimates if we know the "real" value. One way we could address this problem is by adding official census data directly to the new [census table](https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/src/data/census.csv).

**Comment by themonk911** [comment]
This is a duplicate of #158 closing.
