### ISSUE TITLE
geography shapefile

### ISSUE THREAD

**Issue by jzamalloa1** [GoogleCloudPlatform/covid-19-open-data#149]
Hi,

This is more of a request but I was wondering if there is a way to provide geometries like the ones found here:

https://gadm.org/download_country_v3.html

for keys in the geography file (or a separate file)?

Thank you

**Comment by owahltinez** [comment]
Hi @jzamalloa1, we are trying to figure out a good way to share the shapefiles since they can be pretty big. I'm not sure if it will be possible at all, since they are generally pretty hard to work with and not very useful -- we would rather process them and share the useful data from them such as land area, population density, etc.

In the meantime, you can refer to this script which downloads all the shapefiles for our regions: https://github.com/GoogleCloudPlatform/covid-19-open-data/blob/main/src/scripts/download_shapefiles.py. Keep in mind that only regions with an attached OpenStreetMap ID will have a shapefile, and currently that's only ~30% of them.

**Comment by jzamalloa1** [comment]
Great, thank you!
