### ISSUE TITLE
Inconsistent population data.

### ISSUE THREAD

**Issue by alvarosg** [GoogleCloudPlatform/covid-19-open-data#158]
From the demographics table:

Some countries seem to lack total population, while they do have other population features. Maybe this is expected, as there aren't columns for non-binary genders, so you could not just add them up.

![image](https://user-images.githubusercontent.com/12649253/92642993-f5dd4c00-f2d8-11ea-8f2b-a458da0ada11.png)

However, in 729 out of all sites, the summed female and male population is larger than the total population by more than 20% the total population value, for example, In Andorra the sum of female and male population seems to almost double the total population.  This is very suspicious (unless ~70% of the population in Andorra identify themselves as both female and male).

![image](https://user-images.githubusercontent.com/12649253/92642942-e0682200-f2d8-11ea-9afd-235a003c1c4a.png)

**Comment by owahltinez** [comment]
Thanks for bringing this up, these are very good questions.

> Some countries seem to lack total population, while they do have other population features. Maybe this is expected, as there aren't columns for non-binary genders, so you could not just add them up.

This is definitely a bug. I'll look into why this is happening.

> However, in 729 out of all sites, the summed female and male population is larger than the total population by more than 20% the total population value

This may or may not be a bug. I will document this better, but population counts can come from different places:
1. For some regions, we have official census data in which case that's the value we use
1. Countries have population estimates from WorldBank, which I believe uses the same methodology as the UN
1. Most other regions have population from Wikidata (i.e. Wikipedia) which we use as a fallback
1. If none of the other sources are available, we use estimates from WorldPop which are done using the region's shapefile and some fancy ML magic

The tricky bit is that what I described above applies *independently* to each field. So, for example, Andorra has a population of 77,142 probably coming from WorldBank's estimate. However, I believe that the male/female and age breakdown estimates are only available via the WorldPop data source, which uses significantly different estimation methods which are often very accurate but sometimes greatly differ from other data sources (especially for small regions).

All that said, it's still possible that we have a completely wrong estimate, if the shapefile associated with the region is wrong. 

In the next version of the schema, we will consider providing only ratios instead of total counts to avoid confusion. Although that might mask some issues like Andorra having `population ~= population_male`

**Comment by owahltinez** [comment]
Sorry for the delay. I finally took some time to investigate why `GG` didn't have total population. It turns out [its Wikidata entry](https://www.wikidata.org/wiki/Q3311985) was missing the population value. I edited it myself, so `GG` should have total population within the next 12-24 hours.
