### ISSUE TITLE
Mobility trends last updated 11/9

### ISSUE THREAD

**Issue by alksak** [GoogleCloudPlatform/covid-19-open-data#192]
Thank you for the availability of these data. We use mobility data to calibrate our projections models (an example https://covid-analysis.com/country/Greece ).

Is there a specific reason that they are not updated after 13/9 ? Can we continue using them in our research?

**Comment by owahltinez** [comment]
Thanks for reporting this! There have been some changes in the Google Mobility Reports, as per the [project page](https://www.google.com/covid19/mobility/):
![image](https://user-images.githubusercontent.com/41451293/94027985-7300ca80-fd89-11ea-9baa-70c589d9f634.png)

It looks like some data is now updated as of yesterday, and since this is not something actionable for us I'll be closing this issue. But feel free to continue the conversation here if you have any more questions.
