### ISSUE TITLE
6-hourly updates of epidemiology data are missing for the last 27 hours

### ISSUE THREAD

**Issue by winwiz1** [GoogleCloudPlatform/covid-19-open-data#194]
The file `epidemiology.csv` was last updated Mon, 21 Sep 2020 21:58:56 GMT

Updating the file every 6 hours is one of the key competitive advantages of this repository. To maintain this advantage I'd suggest to implement a watchdog service. It would use GCP Alerting Policy to send emails if an update was skipped escalating to SMS if several consecutive updates are missing.

**Comment by winwiz1** [comment]
Next update took place at  Wed, 23 Sep 2020 02:57:08 GMT

**Comment by jaepil-choi** [comment]
Where does it states that the file is updated every 6 hours? I can only read descriptions about basic schema but can't find information about data arrival anywhere.

**Comment by winwiz1** [comment]
> Where does it states that the file is updated every 6 hours?

It is not documented but it was de facto update frequency for days. Documenting when updates take place (e.g. stating 15 min update window or something similar) would be a good idea and in line with what others do.

**Comment by owahltinez** [comment]
It looks like the `epidemiology.csv` file was finally updated yesterday, but it has not been updated again since then so I'll keep an eye on it. We're dealing with some stability issues which causes jobs to fail more often than normal, I'll keep this issue open until that is resolved.

> To maintain this advantage I'd suggest to implement a watchdog service. It would use GCP Alerting Policy to send emails if an update was skipped escalating to SMS if several consecutive updates are missing.

Thanks for the suggestion, this is a great idea. Unfortunately, we don't have the resources necessary to have someone on-call for this project. I like the idea of a watchdog service that can restart the data pipeline automatically, though.

**Comment by winwiz1** [comment]
Thanks for the update!

**Comment by owahltinez** [comment]
The pipeline is now back to regular data updates. We're still working on making things more reliable and increase frequency of updates, but there's no timeline for that yet.
