### ISSUE TITLE
Please specify the time of data arrival. 

### ISSUE THREAD

**Issue by jaepil-choi** [GoogleCloudPlatform/covid-19-open-data#196]
The current dataset is great but it doesn't have the time of arrival so it's hard to tell when it's actually filled. 
For example, a recent couple of days' covid death/cases, etc are empty but we all know it will be filled within a day or two. 

So how do I know exactly when the data has been updated? I'm querying the database with Python API so if the data updates regularly, I can just query the data once or twice a day.

**Comment by owahltinez** [comment]
The frequency at which data is updated depends entirely on the underlying data sources. Some data sources update daily, some update every few days. We try to keep up with the most frequent data source such that we're never more than a day behind, but we don't have a strict SLA.

**Comment by winwiz1** [comment]
> The frequency at which data is updated depends entirely on the underlying data sources.

This should not be the case.  One of the reasons such an unwanted dependency exists is that there are hundreds of URLs (~250 countries and I assume 2-4 URLs per country) to download data from and this is done synchronously/sequentially using the `requests` library. 

Please consider performing downloads asynchronously/in parallel.

**Comment by owahltinez** [comment]
> Please consider performing downloads asynchronously/in parallel

I'm not sure what this is referring to. All downloads are asynchronous. If a data source has not changed in the past 24 hours, it does not matter how frequently we download it, the data will not be any different.

**Comment by winwiz1** [comment]
I think there might be 3 issues here:

1. A more definitive schedule for when the production bucket gets updated regardless of the underlying data so that users know when to load it (and can avoid periodic checking/polling) - this sounds like what the OP is after? I'm keen on it as well.
2. When the data sources themselves get updated - of course the code in this repository cannot control it.
3. Possible improvements in runtime performance when it comes to downloading all those URLs - i.e. in parallel & with timeouts so they don't hold up a scheduled release. This parallelism can be achieved through either asynchronicity or multiprocessing or both.

**Comment by owahltinez** [comment]
Got it, thanks for the clarification.

> A more definitive schedule for when the production bucket gets updated regardless of the underlying data so that users know when to load it (and can avoid periodic checking/polling) - this sounds like what the OP is after? I'm keen on it as well.

Fair enough. We are currently tweaking our infrastructure and will be able to provide more accurate times once those changes land, since we are hoping to achieve a more stable data pipeline with far fewer job failures. In the meantime, I would suggest going by the same schedule which we use to publish our data in BigQuery which I believe is 2 AM UTC once a day.

> When the data sources themselves get updated - of course the code in this repository cannot control it.

Correct.

> Possible improvements in runtime performance when it comes to downloading all those URLs - i.e. in parallel & with timeouts so they don't hold up a scheduled release. This parallelism can be achieved through either asynchronicity or multiprocessing (the current approach) or both.

This is already how things are being done. A possibly unwanted result is that not all files are updated with the same frequency. For instance, the job which updates `epidemiology.csv` is different to the job which aggregates data into `main.csv`. Even if the schedules were the same, one job might fail and the other succeed.

And that's only referring to the jobs which move data into the publicly accessible bucket. Almost all the "raw" data is being downloaded and pre-processed hourly, but the outputs go into a private project bucket.

**Comment by owahltinez** [comment]
I have added the following section to the main README file: https://github.com/GoogleCloudPlatform/covid-19-open-data#data-updates. It's still a bit vague because we don't want to commit to any sort of SLA / SLO.

We now have a more stable pipeline; all tables are being updated at least twice a day and the epidemiology, hospitalizations, by-age and by-sex tables are being updated every 1-2 hours.
