### ISSUE TITLE
Google Cloud Storage not serving files gzipped

### ISSUE THREAD

**Issue by jmullo** [GoogleCloudPlatform/covid-19-open-data#244]
It seems that files are transferred uncompressed, which makes loading epidemiology.json (currently >140MB) into a browser quite fun :(

**Comment by owahltinez** [comment]
This is a tough one. It [looks like](https://stackoverflow.com/questions/40895706/enabling-gzip-on-google-cloud-storage-static-files) we would have to upload the data already compressed to GCS. We would probably need to change the file name from X.json to X.json.gz, which we could do but it will take us a bit to figure out how to upload with the right format and metadata flags.

Another option is to use the individual JSON files for each location. You can download the index.json file every now and then (since it changes infrequently) and then use the keys from there to download each JSON file to get all of the location's data which you can parallelize and it's only ~300KB per location.

**Comment by jmullo** [comment]
That 140MB compresses into something like 20MB, so it would be a huge decrease in transferred data for all users. I warmly recommend doing that if possible.

**Comment by owahltinez** [comment]
Turns out there is a very cool feature which allows us to upload files as GZIP but GCS will automatically decompress them as needed: https://cloud.google.com/storage/docs/transcoding#decompressive_transcoding

I just merged #257 to compress all JSON files and it appears to be working as far as I can tell. Can you please verify?

**Comment by jmullo** [comment]
Verified, works as expected. Can be applied to .csv as well?

**Comment by owahltinez** [comment]
Great! That was way easier than I anticipated.

In theory, this can be applied to the CSV files as well. We are currently looking at ways to make main.csv more manageable, so this is a potential solution to that. We're also considering archiving it into a ZIP file, which can be read directly by many tools.

**Comment by owahltinez** [comment]
We'll probably keep the CSV files as-is, and we will be providing a compressed version of the main table only. Closing since this the main issue (JSON files) is resolved.
