### ISSUE TITLE
United Kingdom total_deceased data broken

### ISSUE THREAD

**Issue by jmullo** [GoogleCloudPlatform/covid-19-open-data#246]
Stays the same between 2020-03-18 and 2020-05-27.

**Comment by owahltinez** [comment]
@themonk911 can you please take a look? I just checked, and the zeroes appear to be coming from `Cov19API`.

Perhaps a potential solution is to not report confirmed and deceased counts for key `GB` since we already have that data coming from two other sources (WHO and ECDC). Number of tests should still be reported though.

But before we do that, it would be nice to understand why this is happening in case there is a more serious error.

**Comment by themonk911** [comment]
Yeah it's even reflected on the main UK govt dashboard https://coronavirus.data.gov.uk/deaths. I'll look at whether querying for deaths by publish date would fix this issue.

**Comment by themonk911** [comment]
Okay, so it seems like between those dates the UK govt is not reporting "Deaths within 28 days of positive test by date deceased" but is reporting "Deaths within 28 days of positive test by date reported". I could switch GB to use the latter numbers, but they will be different from the former.

**Comment by owahltinez** [comment]
Let me try to rephrase that to see if I'm understanding the problem correctly.

UK reports deaths in two ways, by date deceased and by date reported. I'm guessing that the difference is the delay between a person dying and the confirmation of that death being caused by COVID-19.

Having deaths without the delay would be good, because it's more timely information so it can be better compared with other metrics without having to adjust the date. However, the data is incomplete.

On the other hand, deaths by reported date are complete. They are also consistent with how other locations report deaths.

If we want to have a complete view of deaths, we have to either:
1. Pick a date and switch from deaths by reported date to deaths by date deceased on that date.
2. Use deaths by reported date everywhere.

Any other potential solutions? What do you think would be the best way to resolve this?

**Comment by themonk911** [comment]
I think we should use deaths by reported date everywhere for L1. I'm not sure whether we also want to make this change for L2 or not, for consistency between levels.

**Comment by themonk911** [comment]
Honestly- I think this is a bug on PHE's side, they have the required data and correctly show it for L2. I'll send an email to their feedback portal to see if we can get this resolved on that side. We could make the change to publishdate for L1 and change back when they fix the issue?

**Comment by owahltinez** [comment]
That sounds great, thanks for following up!
