### ISSUE TITLE
United Kingdom drop in total_deceased on 2020-08-02

### ISSUE THREAD

**Issue by jmullo** [GoogleCloudPlatform/covid-19-open-data#263]
Is that perhaps caused by the latest fix?

**Comment by themonk911** [comment]
When you say 'drop' do you mean that an N/A is being reported for that date?

**Comment by jmullo** [comment]
2020-08-01: 46193
2020-08-02: 41207

**Comment by themonk911** [comment]
Ah gotcha - thanks for reporting. This is coming from a merge between two sources, up to 2020-08-01 we have numbers from https://raw.githubusercontent.com/tomwhite/covid-19-uk-data/master/data/covid-19-cases-uk.csv, but the second number is coming from the WHO and these disagree. @owahltinez I think we should remove the Tom White data source since it is no longer updated. On another note, I think we should reinstate the primary PHE source since they appear to have fixed the original issue. WDYT?
