### ISSUE TITLE
Thank you and request

### ISSUE THREAD

**Issue by jzamalloa1** [GoogleCloudPlatform/covid-19-open-data#31]
Thank you for maintaining this repo! Is it possible to include the Continent column corresponding to each location?

**Comment by owahltinez** [comment]
Hi @jzamalloa1, thank you for the kind words. What are you trying to accomplish with the information about continent? We initially decided not to include it as part of the metadata because it's not informative in terms of any of the statistics that we collect.

If you care about geography, then the coordinates might be better suited to determine regional clusters (although that does not always correlate to travel flows). If you care about cultural or historical groupings, there are better ways to discriminate other than continents -- for example breaking down Asia into India, South East Asia, China and Japan + Korea might be significantly more useful.

**Comment by jzamalloa1** [comment]
Thank you owahltinez. I was trying to look for similar historical patterns across regions and wanted to check if case patterns were translatable within geographies. In that sense I see your point, it might make sense to use coordinates (in lieu of travel flows) rather than continents.

**Comment by themonk911** [comment]
It seems like this issue has been resolved, if not please reopen.
