### ISSUE TITLE
Advice on visualising this data

### ISSUE THREAD

**Issue by umaar** [GoogleCloudPlatform/covid-19-open-data#335]
Hi, and thanks for making this available to use! As a little side project, I was intending to visualise this data on a map based visualisation. The question/challenge is: is there a standard/best practice for which level of granularity to use, and how to do it? 

For example:

![image](https://user-images.githubusercontent.com/381495/100528366-fb5d7a80-31d3-11eb-858e-21068e9bba65.png)

Rather than just showing ~1 big blob for almost all of the UK, I think it'd be more valuable to show a "blob" (a.k.a. a marker) for each city - of which there are 69 in the UK. But taking a quick glance at your data, I can see there is indeed city-level covid data for the UK (and IMO would be helpful to use), but is there a technique to figure our what exactly is a city? And what happens when 1 city has no data, is it best to then "defer" to visualising it at the country level? And how would I scale these for the whole world! If it's safer/simpler/more reliable to only do countries, that's also fine, but curious on the "right" way of doing that based on the available data.

Ha, probably highlighting my amateurism at mapping systems, but thought I'd ask in case this is a solved problem.

**Comment by owahltinez** [comment]
Hi @umaar, you can take advantage of the hierarchical nature of our locations. Countries have `aggregation_level=0`, admin level 1 regions have `aggregation_level=1` and admin level 2 regions have `aggregation_level=2`. For the purpose of visualization, it's probably safer to ignore `aggregation_level=3`, although that's where most of the city-level data lives.

If you are interested in city-level data, I would recommend maintaining a list of known keys with `aggregation_level=3` which you know are cities. This is because there may be other locations which are not cities in that aggregation level.
