### ISSUE TITLE
No subregion1 level data for some countries

### ISSUE THREAD

**Issue by jzamalloa1** [GoogleCloudPlatform/covid-19-open-data#58]
Hi,

I noticed in today's pull that level 1 data for a few countries including Peru, Colombia and Italy. Can you check on this please?

Thank you

**Comment by owahltinez** [comment]
Thanks for reporting this issue. Which table is missing admin level 1 data?

**Comment by jzamalloa1** [comment]
This would be for main.csv. For example, Peru-Arequipa or Italy-Sicily at aggregation level 1 display a column of NAs for new_confirmed.

**Comment by owahltinez** [comment]
I just merged a pull request which fixes this issue. The main.csv file should pick up the changes within the next couple of hours.

The problem was that some data sources, like Peru, provide data for multiple tables. In this case, the data was going to either epidemiology.csv *or* by-age.csv *or* by-sex.csv. The change makes sure that the same data source can propagate data across an arbitrary number of tables.

This wasn't a problem before, but we recently "improved" our CSV output functions to strictly follow a schema, so now a data source will output a different file for each table instead of sharing it.

**Comment by jzamalloa1** [comment]
Sounds great, thank you.
